name: Main
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'crowdin.yml'
      - 'data/translations/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yml'
      - '.gitignore'
      - 'crowdin.yml'
      - 'data/translations/**'
jobs:
  validate-metainfo:
    name: Validate metainfo
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install AppStream metadata utility
        run: |
          sudo apt-get update
          sudo apt-get install appstream-util

      - name: Validate metainfo
        run: appstream-util validate-relax data/io.crow_translate.CrowTranslate.metainfo.xml

  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Check formatting
        uses: DoozyX/clang-format-lint-action@v0.15
        with:
          clangFormatVersion: 12

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install extra-cmake-modules libqt5x11extras5-dev libqt5websockets5-dev qttools5-dev qtmultimedia5-dev libkf5wayland-dev libtesseract-dev ninja-build

      - name: Build
        run: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D WITH_PORTABLE_MODE=ON -D CMAKE_INSTALL_PREFIX=install -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror"
          cmake --build build --parallel 2 --target install

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: crow-translate-linux
          path: install/**
