name: Release
on:
  release:
    types: [created]
jobs:
  pack:
    name: Pack source tarball
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Create source tarball
        run: |
          SOURCE_NAME=${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}
          git ls-files | \
          tar --exclude-vcs --transform "s|^|$SOURCE_NAME/|S" -ca -T - -f ../$SOURCE_NAME-source.tar.gz

      - name: Upload source tarball
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '../*.tar.gz'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]

    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install apt packages
        if: matrix.arch == 'amd64'
        run: |
          sudo apt-get update
          sudo apt-get install extra-cmake-modules libqt5x11extras5-dev libqt5websockets5-dev qttools5-dev qtmultimedia5-dev libkf5wayland-dev libtesseract-dev rpm qt5-default qtgstreamer-plugins-qt5 gstreamer1.0-plugins-good gstreamer1.0-alsa gstreamer1.0-pulseaudio libqt5multimedia5-plugins qt5-style-plugins ninja-build
          sudo apt-get remove qt5-gtk-platformtheme # Do not use libqgtk3.so because of https://bugreports.qt.io/browse/QTBUG-72506

      - name: Install linuxdeploy
        if: matrix.arch == 'amd64'
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt gstreamer

      - name: Build
        if: matrix.arch == 'amd64'
        run: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CPACK_GENERATOR="DEB;RPM;External"
          cmake --build build --target package --parallel 2 --config Release

      - name: Build in Ubuntu 20.04 Docker image
        uses: uraimo/run-on-arch-action@v2.5.0
        if: matrix.arch != 'amd64'
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          dockerRunArgs: --volume "${PWD}:/repo"
          install: |
            apt-get update -y
            apt-get install -y libxcb1-dev extra-cmake-modules libqt5x11extras5-dev libqt5websockets5-dev qttools5-dev qtmultimedia5-dev libkf5wayland-dev libtesseract-dev g++ git rpm libssl-dev wget ninja-build
            # Install fresh CMake due to problems with QEMU: https://gitlab.kitware.com/cmake/cmake/-/issues/20568
            # https://apt.kitware.com currently have an issue with unresolved dependency on arm, build manually
            CMAKE_VERSION=3.21.1
            wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION.tar.gz
            tar -zxvf cmake-$CMAKE_VERSION.tar.gz
            cd cmake-$CMAKE_VERSION
            ./bootstrap --generator=Ninja
            ninja install -j 2
          run: |
            cmake -S /repo -B /repo/build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CPACK_GENERATOR="DEB;RPM;External"
            cmake --build /repo/build --target package --parallel 2

      - name: Upload
        uses: AButler/upload-release-assets@v2.0
        with:
          files: build/{*.AppImage,*.AppImage.zsync,*.deb,*.rpm}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
